Popup window
Mike-devloper/Portfolio-Mobile pull request #10
Opened 2022-09-07 12:04 UTC by Mike-devloper

Add popup window for mobile and desktop

2022-09-07 12:41 UTC, omarsalem7 requested changes
Hi @Mike-devloper 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper title ✔️
- Correct git-flow ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 12:41 UTC, omarsalem7 commented on styles.css
> +}
- [ ] Kindly fix the width of the buttons to match it like Figma, the following image in iphone6/7/8
>![image](https://user-images.githubusercontent.com/53402600/188879653-f836c5ff-c200-4b23-93bc-d07a6e09b4fa.png)

2022-09-07 12:41 UTC, omarsalem7 commented on index.html
>                          </form>
- [ ] Consider the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for the projects list should be removed, and instead it should be added via JavaScript. Also, consider using the same data for both works projects and models for them.

2022-09-07 18:06 UTC, ShadyShawkat approved these changes
## Hi @Mike-devloper, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 
- Good overall design ✔️ 
- Your code is clean and well documented ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 19:36 UTC, merged

2022-10-20 08:10 UTC, oguntayomicheal commented on index.html
>                          </form>
Hello @omarsalem7, thanks for your review, it is really helpful. I will implement the suggested changes.

2022-10-20 08:11 UTC, oguntayomicheal commented
Hello @ShadyShawkat, thanks for your review.