Desktop homepage
Mike-devloper/Portfolio-Mobile pull request #5
Opened 2022-08-25 10:06 UTC by Mike-devloper

Add media query to styles.css file
Update index.html file and image files for desktop version

2022-08-25 11:11 UTC, roshan-bajgain requested changes
Hi @Mike-devloper, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
- [ ] I would suggest you please make changes to whatever I gave on the desktop version as it is creating the same problems on the mobile version as well. Please fix it
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:11 UTC, roshan-bajgain commented on index.html
>              </div>
- [ ] I would suggest please decrease the gap between the list and provide padding on it. See image below for reference.
### Your design
![your](https://user-images.githubusercontent.com/81727988/186647713-48958de0-4ac7-4b82-9036-2a66c998540d.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/186647758-e384f4a3-9b14-495f-890a-ed690003bc90.png)

2022-08-25 11:11 UTC, roshan-bajgain commented on index.html
> +                        </div>
- [ ] I would suggest you please decrease the spacing between the `Get in touch` buttons and the input field and decrease the padding left and right as well.
### Image
![hiiiiiiiiisssssss](https://user-images.githubusercontent.com/81727988/186648830-4f03e46c-fd33-442c-99d8-32cd2b4621c8.png)

2022-08-25 14:39 UTC, danmainah approved these changes
Hi @Mike-devloper , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used

## Optional suggestions

- [ ] [optional] @Mike-devloper great work implementing the changes requested, kindly check your readme file, and fix the title and description section.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 07:54 UTC, merged

2022-10-20 07:47 UTC, oguntayomicheal commented on index.html
> +                        </div>
Hi @roshan-bajgain, thanks for the review, all suggested changes will be implemented.

2022-10-20 07:53 UTC, oguntayomicheal commented
Hi @danmainah, thanks for approving my code. I will implement the optional changes.