Mobile menu
Mike-devloper/Portfolio-Mobile pull request #9
Opened 2022-09-05 15:46 UTC by Mike-devloper

Add mobile menu to index.html file
Add mobile menu styles to the styles.css file
Add myscript.js file

2022-09-05 18:33 UTC, vickymarz requested changes
Hi @Mike-devloper, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-05 18:33 UTC, vickymarz commented on index.html
> +
- [ ] Good job adding the mobile menu 👍🏽 . I think it will be better if you add the appropriate spacing between your mobile menu lists to match the Figma design template chosen 😄 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/188499906-fbd2b6be-20b6-4fcd-8e04-07d3ef5564b3.png)  | ![image](https://user-images.githubusercontent.com/63473584/188499929-004eaec9-0979-4e02-8133-a58fefe734ea.png)  |

2022-09-05 18:33 UTC, vickymarz commented on index.html
> +    </div>
- [ ] Good job adding the mobile menu 👍🏽 . From the design template you chose, I can see that the mobile menu covers the entire viewport height which is not the case in your own design. I would recommend you use `min-height: 100vh` on the mobile menu container so that its height can fit the viewport height 👍🏽 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/188500180-1507da29-c3c8-46c9-8194-987ec136d778.png)  | ![image](https://user-images.githubusercontent.com/63473584/188500222-d9e071b8-5829-44a6-9efd-4cd12ce197b5.png)  |

2022-09-05 18:33 UTC, vickymarz commented on myscripts.js
> +function mobileMenu (){
[OPTIONAL]

- I would recommend you use the arrow function which is a modern es6 syntax as it can make your code simpler and neater 😄

2022-09-05 18:33 UTC, vickymarz commented on myscripts.js
> +    var x = document.getElementById("menu")
[OPTIONAL]

- I think it would be better if you write a more descriptive variable name so that your code can be more readable and maintainable by other developers 👍🏽

2022-09-05 20:35 UTC, ShahierNashaat approved these changes
Hi @Mike-devloper, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-05 20:42 UTC, Mike-devloper commented on myscripts.js
> +function mobileMenu (){
Please can you send a link for me to check out the arrow function @vickymarz

2022-09-05 20:43 UTC, merged

2022-10-20 08:06 UTC, oguntayomicheal commented on myscripts.js
> +    var x = document.getElementById("menu")
Thanks for the review, all suggested changes will be implemented.

2022-10-20 08:08 UTC, oguntayomicheal commented
Hi @ShahierNashaat, thanks for your review.